### PR TITLE
Add support to specify plugins to load

### PR DESCRIPTION
**Pull request by claudioluciano**
Hey, i add support to specify plugins to load, but i think is not the best approach bacause when the modules are found we have only the file name, so on this initial version we are checking only by file name.
I think we could check the class name but only after the module is load

### CODE REVIEW

**Comment by mammo0** [comment]
Yes, your approach will only allow to import specific plugins by **module name** (which is basically the file name).

But I think importing by **class name** is better, because the the loader tests also for a specific class type.

**Comment by mammo0** [comment]
@claudioluciano I've made some changes. Does this fit your needs?

**Comment by claudioluciano** [comment]
@mammo0 Meets perfectly, thank you very much :)

**Comment by mammo0** [comment]
created new release: https://github.com/mammo0/py-simple-plugin-loader/releases/tag/v1.6

**Pull request merged**
